"""empty message

Revision ID: 16fa657bca74
Revises: 
Create Date: 2019-11-19 20:16:12.040416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fa657bca74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('name', sa.String(), nullable=True))
    op.add_column('films', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'year')
    op.drop_column('films', 'name')
    # ### end Alembic commands ###
