version: "3.7"
services:
  homework:
    build: .
    ports:
    - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl http://127.0.0.1:8000/health_check/"]
      interval: 10s
      timeout: 5s
      retries: 5
