"""empty message

Revision ID: 0463bbc8181e
Revises: 26ffb1e81e59
Create Date: 2019-12-11 21:22:45.851479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0463bbc8181e'
down_revision = '26ffb1e81e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('edition', sa.String(), nullable=False),
    sa.Column('edition_year', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('book_owner',
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['books.name'], )
    )
    op.drop_table('book')
    op.add_column('users', sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_id')
    op.create_table('book',
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('edition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('edition_year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('translation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='book_pkey')
    )
    op.drop_table('book_owner')
    op.drop_table('books')
    # ### end Alembic commands ###
