"""empty message

Revision ID: 08e9550f993a
Revises: 50e089684e39
Create Date: 2019-12-11 21:55:51.504600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e9550f993a'
down_revision = '50e089684e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('owner', sa.String(), nullable=True))
    op.create_foreign_key(None, 'library', 'books', ['owner'], ['book_owner'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.drop_column('library', 'owner')
    # ### end Alembic commands ###
