"""empty message

Revision ID: 169a27cf0b85
Revises: 
Create Date: 2019-11-27 19:59:07.878078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169a27cf0b85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('edition', sa.String(), nullable=False),
    sa.Column('edition_year', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('library', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('book')
    # ### end Alembic commands ###
