"""empty message

Revision ID: 4d3bacae7a83
Revises: ce5d22d4106d
Create Date: 2020-02-09 19:33:48.182119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3bacae7a83'
down_revision = 'ce5d22d4106d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_owner_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_owner_id_fkey', 'books', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
