"""empty message

Revision ID: 50e089684e39
Revises: 0463bbc8181e
Create Date: 2019-12-11 21:48:41.998788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e089684e39'
down_revision = '0463bbc8181e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('book_owner')
    op.add_column('books', sa.Column('book_owner', sa.String(), nullable=True))
    op.drop_column('users', 'library')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('library', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('books', 'book_owner')
    op.create_table('book_owner',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['name'], ['books.name'], name='book_owner_name_fkey')
    )
    op.drop_table('library')
    # ### end Alembic commands ###
