"""empty message

Revision ID: 54785e70fc5b
Revises: e6bb8b722679
Create Date: 2020-02-08 16:04:08.830835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54785e70fc5b'
down_revision = 'e6bb8b722679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_books')
    op.drop_table('library')
    op.add_column('books', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    op.create_table('library',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_title'], ['books.book_title'], name='library_book_title_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='library_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='library_pkey')
    )
    op.create_table('user_books',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='user_books_book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_books_user_id_fkey')
    )
    # ### end Alembic commands ###
