"""empty message

Revision ID: ce5d22d4106d
Revises: cd6a50d211cb
Create Date: 2020-02-09 19:24:52.361654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5d22d4106d'
down_revision = 'cd6a50d211cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libraries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='libraries_pkey')
    )
    # ### end Alembic commands ###
