"""empty message

Revision ID: fa908daa5912
Revises: 2b64eef23e17
Create Date: 2020-01-02 20:38:30.783442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa908daa5912'
down_revision = '2b64eef23e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('library_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books', 'library', ['library_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'library_id')
    # ### end Alembic commands ###
