# Generated by Django 3.0.1 on 2020-01-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=5, verbose_name='room_number')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mycore.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='First name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last name')),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone num')),
                ('photo', models.ImageField(blank=True, help_text='Photo of the tenant', null=True, upload_to='tenant', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='mycore.Room')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_out_date', models.DateTimeField()),
                ('key_in_date', models.DateTimeField()),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mycore.Tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['first_name', 'last_name'], name='mycore_tena_first_n_59e684_idx'),
        ),
        migrations.AddField(
            model_name='journal',
            name='key_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mycore.Key'),
        ),
    ]
