# Generated by Django 3.0.1 on 2020-01-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0002_auto_20200126_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guests_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
