# Generated by Django 3.0.1 on 2020-01-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0002_auto_20200121_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mycore.Room')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='maximum_number_of_guest',
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_out_date', models.DateTimeField()),
                ('key_in_date', models.DateTimeField()),
                ('key_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mycore.Key')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mycore.Tenant')),
            ],
        ),
    ]
