"""empty message

Revision ID: 09e3fe8b4e22
Revises: 05a8515a9f09
Create Date: 2019-11-19 18:32:38.486923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e3fe8b4e22'
down_revision = '05a8515a9f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'staff', ['passport_ID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='unique')
    # ### end Alembic commands ###
