"""empty message

Revision ID: 565930b9d25d
Revises: a1c6212088f5
Create Date: 2019-11-21 18:11:48.877080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565930b9d25d'
down_revision = 'a1c6212088f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('address', sa.String(), nullable=False))
    op.drop_column('tenants', 'street')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tenants', 'address')
    # ### end Alembic commands ###
