"""empty message

Revision ID: e2fc6da27338
Revises: 
Create Date: 2019-11-18 21:47:49.042632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fc6da27338'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rooms', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rooms', 'tenant_ID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('rooms_level_key', 'rooms', type_='unique')
    op.drop_constraint('rooms_price_key', 'rooms', type_='unique')
    op.drop_constraint('rooms_status_key', 'rooms', type_='unique')
    op.drop_constraint('rooms_tenant_ID_key', 'rooms', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('rooms_tenant_ID_key', 'rooms', ['tenant_ID'])
    op.create_unique_constraint('rooms_status_key', 'rooms', ['status'])
    op.create_unique_constraint('rooms_price_key', 'rooms', ['price'])
    op.create_unique_constraint('rooms_level_key', 'rooms', ['level'])
    op.alter_column('rooms', 'tenant_ID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rooms', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rooms', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rooms', 'level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
