"""empty message

Revision ID: eb27782f043d
Revises: 
Create Date: 2019-11-20 20:03:25.118091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb27782f043d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenants_address_key', 'tenants', type_='unique')
    op.drop_constraint('tenants_age_key', 'tenants', type_='unique')
    op.drop_constraint('tenants_city_key', 'tenants', type_='unique')
    op.drop_constraint('tenants_sex_key', 'tenants', type_='unique')
    op.drop_constraint('tenants_street_key', 'tenants', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tenants_street_key', 'tenants', ['street'])
    op.create_unique_constraint('tenants_sex_key', 'tenants', ['sex'])
    op.create_unique_constraint('tenants_city_key', 'tenants', ['city'])
    op.create_unique_constraint('tenants_age_key', 'tenants', ['age'])
    op.create_unique_constraint('tenants_address_key', 'tenants', ['address'])
    # ### end Alembic commands ###
